# This is a generated file. Not intended for manual editing.
services:
  aplicacaoteste.host:
    build:
      context: "/Users/r.marcel/Documents/Projects/teste-orleans/AplicacaoTeste"
      dockerfile: "AplicacaoTeste.Host/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "aplicacaoteste.host:dev"
    ports:
    - "127.0.0.1:57011:57000"
    - "127.0.0.1:57211:57200"
    - "127.0.0.1:57411:57400"
    volumes:
    - "/Users/r.marcel/Documents/Projects/teste-orleans/AplicacaoTeste/AplicacaoTeste.Host:/app:rw"
    - "/Users/r.marcel/Documents/Projects/teste-orleans/AplicacaoTeste:/src:rw"
    - "/Users/r.marcel/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/r.marcel/.local/share/JetBrains/RiderRemoteDebugger/2024.3.5/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/r.marcel/Library/Logs/JetBrains/Rider2024.3/DebuggerWorker/JetBrains.Debugger.Worker.2025_2_20_15_33_12:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
